<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.brasatech</groupId>
		<artifactId>medpulse</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../../../pom.xml</relativePath>
	</parent>
	<artifactId>medpulse-adapter-out-repository</artifactId>
	<name>medpulse-adapter-out-repository</name>
	<description>Persistence repository outbound adapter for MedPulse</description>

	<dependencies>
		<!-- Application Dependency -->
		<dependency>
			<groupId>es.brasatech</groupId>
			<artifactId>medpulse-application</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- JPA Persistence -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<!-- H2 database support -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>
</project>
